##
## Mail locations & namespaces
##
mail_location = maildir:/var/mail/vhosts/%d/%n/Maildir

namespace inbox {
  inbox = yes
  separator = /

  # Gmail-like: labels map to sub-folders under a hidden namespace
  mailbox Trash {
    auto = subscribe
    special_use = \Trash
  }
  mailbox Drafts {
    auto = subscribe
    special_use = \Drafts
  }
  mailbox Sent {
    auto = subscribe
    special_use = \Sent
  }
  mailbox Archive {
    auto = subscribe
    special_use = \Archive
  }
  mailbox Spam {
    auto = subscribe
    special_use = \Junk
  }
}

mail_uid = 5000
mail_gid = 5000
mail_privileged_group = mail
first_valid_uid = 5000
last_valid_uid = 5000

mail_plugins = $mail_plugins quota acl
